### ISSUE TITLE
Is it possible to not convert inline comments?

### ISSUE THREAD

**Issue by ghost** [postcss/postcss-scss#138]
I'm using this as a codemod and don't want it to touch comments, but everything I try converts them into block comments.

example:

```js
const postcssScss = require('postcss-scss');
const postcss = require('postcss')

const scss = `div {
  padding: 0; // comment
}`;

postcss().process(scss, {syntax: postcssScss}).then(result => {
  const node = result.root.nodes[0].nodes[0];
  node.assign({prop: 'spacing'})
  console.log(result.root.toString())
})
```

result:

```css
div {
  spacing: 0; /* comment*/
}
```

desired:

```css
div {
  spacing: 0; // comment
}
```

Thanks!
