### ISSUE TITLE
Strange bug with parsing

### ISSUE THREAD

**Issue by evilebottnawi** [postcss/postcss-scss#16]
Message:
   /sass/compile/_base.scss:23:8: Unknown word
// ::-webkit-scrollbar {
//     width: 15px;
       ^
//

My code:
```scss
@-webkit-viewport {
    width: device-width;
}

@-moz-viewport {
    width: device-width;
}

@-ms-viewport {
    width: device-width;
}

@-o-viewport {
    width: device-width;
}

@viewport {
    width: device-width;
}

// ::-webkit-scrollbar {
//     width: 15px;
//
//     &-track {
//         background: $gray-lighter;
//     }
//
//     &-thumb {
//         background: $gray;
//         &:window-inactive {
//             background: $gray-light;
//         }
//     }
// }

p {
    margin: 0 0 1em;

    &[align="center"] {
        text-align: center;
    }

    &[align="left"] {
        text-align: left;
    }

    &[align="right"] {
        text-align: right;
    }
}
```
