### ISSUE TITLE
bug with interpolation

### ISSUE THREAD

**Issue by evilebottnawi** [postcss/postcss-scss#32]
In libsass:
```scss
.embed-responsive-wrapper {
    @media#{$xs-and-down} {
        display: block;
        width: auto !important;
        max-width: none;
    }
}
```
to
```css
@media (max-width: 767px ) {
  .embed-responsive-wrapper {
    display: block;
    width: auto !important;
    max-width: none;
  }
}
```
In postcss-scss i got error:
```shell
Unknown word

    @media#{$xs-and-down} {
            ^
        display: block;
```

**Comment by ai** [comment]
Thanks. Sorry I will be able for look into it only after CSSConf, May 12

**Comment by evilebottnawi** [comment]
@ai good

**Comment by ai** [comment]
Seems like problem is because `@media` and `#{$xs-and-down}` has no spaces between.

**Comment by ai** [comment]
Here is a simplest test `@media #{$xs-and-down} { }'`.

I am thinking to solve it in PostCSS 5.1.

**Comment by ai** [comment]
Nope, I fixed it with current PostCSS 5.0.x

Done faed14b

**Comment by ai** [comment]
Released in 0.1.8.

**Comment by yugasun** [comment]
@ai I still have the Interpolation bugs, `postcss-scss` can not parse Interpolation syntax.
My scss file:

```scss
$column-count: 6;
.col-#{$column-count} {
    width: 100px;
}
```

Output:

```css
.col-#{6} {
    width: 100px;
}
```

Here is my package.json:

```json
{
  ...
  "scripts": {
    "postcss": "postcss input.scss -o output.css -c postcss.config.js"
  },
  "devDependencies": {
    "postcss-cli": "^4.0.0",
    "postcss-scss": "^1.0.0",
    "precss": "^1.4.0"
  }
}
```

And my postcss.config.js:

```javascript
module.exports = {
  parser: 'postcss-scss',
  plugins: {
    "precss": {},
  }
};
```
