### ISSUE TITLE
Interpolation in media

### ISSUE THREAD

**Issue by evilebottnawi** [postcss/postcss-scss#38]
```scss
$feature: "(monochrome)"; // or "(min-width: 512px)";

@media #{$feature} { }
```
Throw error, but it is valid.
