### ISSUE TITLE
Inline comments start with `//*/` are not converted as expected

### ISSUE THREAD

**Issue by zoubin** [postcss/postcss-scss#41]
Input:

```js
var postcss = require('postcss')
var css = `
.inline-comment {
  color: red;
}
//*/ comments
`
postcss().process(css,
  { syntax: require('postcss-scss') }
)
.then(function (result) {
  console.log(result.root.toString())
})
```

output:
```css
.inline-comment {
  color: red;
}
/**/ comments*/
```

**Comment by ai** [comment]
And what is expected output?

**Comment by zoubin** [comment]
In `/**/ comments*/`, `comments*/` will not be treated as comments by browsers.
Or am I wrong about that? 

The expected output would be something like:

```css
.inline-comment {
  color: red;
}
/**\/ comments*/
```
