### ISSUE TITLE
Doesn't handle `&-foo`

### ISSUE THREAD

**Issue by levity** [postcss/postcss-scss#56]
This valid SCSS:

```scss
bar {
  color: #000;
  &-foo {
    color: #fff;
  }
}
```

should produce `.bar` and `.bar-foo`.
