### ISSUE TITLE
Comment location issue

### ISSUE THREAD

**Issue by vjeux** [postcss/postcss-scss#63]
```css
@font-face  {
  src: url(if(
    $bootstrap-sass-asset-helper,
    twbs-font-path('#{$icon-font-path}#{$icon-font-name}.eot'),
    '#{$icon-font-path}#{$icon-font-name}.eot'
  ));
}

// Catchall baseclass
.glyphicon {
}
```

Outputs for the comment

```js
    {
      "raws": {
        "before": "\n\n",
        "inline": true,
        "left": " ",
        "right": "",
        "text": "Catchall baseclass"
      },
      "type": "css-comment",
      "source": {
        "start": {
          "line": 5,
          "column": 1
        },
        "input": {
          "css": "@font-face  {\n  src: url(if(\n    $bootstrap-sass-asset-helper,\n    twbs-font-path('#{$icon-font-path}#{$icon-font-name}.eot'),\n    '#{$icon-font-path}#{$icon-font-name}.eot'\n  ));\n}\n\n// Catchall baseclass\n.glyphicon {\n}\n",
          "id": "<input css 1>"
        },
        "end": {
          "line": 5,
          "column": 21
        }
      },
      "text": "Catchall baseclass"
    },
```

It says line 5, column 1-21. But this is `'#{$icon-font-pa` and not `// Catchall baseclass`.
