### ISSUE TITLE
Question: How to setup postcss.config.js

### ISSUE THREAD

**Issue by marcobiedermann** [postcss/postcss-scss#69]
Thank you very much for providing `postcss-scss`:
I am trying to setup a webpack config which compiles Scss files to CSS.
My setup looks like this:

webpack.config.js
```js
const path = require('path');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  entry: [
    path.resolve(__dirname, 'client/index.js'),
  ],
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'script.js',
  },
  module: {
    rules: [
      {
        test: /\.scss$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            {
              loader: 'css-loader',
              options: {
                importLoaders: 1,
                sourceMap: true,
              },
            },
            {
              loader: 'postcss-loader',
              options: {
                sourceMap: true,
                config: {
                  path: 'postcss.config.js',
                },
              },
            },
          ],
        }),
      },
    ],
  },
  plugins: [
    new ExtractTextPlugin('styles.css'),
  ],
  resolve: {
    extensions: [
      '.css',
      '.js',
      '.jsx',
      '.scss',
    ],
  },
};
```

postcss.config.js
```js
module.exports = {
  parser: 'postcss-scss',
  sourceMap: true,
};
```

Unfortunately this does not compile my Scss syntax down to CSS.

input:
```scss
.button {

  &--round {
    border-radius: 999em;
  }

}
```

output:
```css
.button {

  &\--round {
    border-radius: 999em;
  }

}
```

expected:
```css
.button--round {
    border-radius: 999em;
}
```
