### ISSUE TITLE
eats css comment in selector list

### ISSUE THREAD

**Issue by evilebottnawi** [postcss/postcss-scss#75]
```scss
.field {
  &[data-very-very-very-very-very-very-very-very-very-very-very-long-field-attribute-name="1"], // Name
  &[data-field-id="2"], // Email
  &[data-field-id="3"], // Postal Code
  {
    background: green;
  }
}
```

Output:
```sh
{ 
  before: '\n  ',
  between: ' // Postal Code\n  ',
  selector: { 
    value: '&[data-very-very-very-very-very-very-very-very-very-very-very-long-field-attribute-name="1"], \n  &[data-field-id="2"], \n  &[data-field-id="3"],',
    raw: '&[data-very-very-very-very-very-very-very-very-very-very-very-long-field-attribute-name="1"], // Name\n  &[data-field-id="2"], // Email\n  &[data-field-id="3"],' },
    semicolon: true,
    after: '\n  ' 
},
```

Seems in `between` we have comment, i don't known it is bug or expected behavior.

Based on issue: https://github.com/prettier/prettier/issues/2686
