### ISSUE TITLE
inline comments are not converted properly

### ISSUE THREAD

**Issue by gera2ld** [postcss/postcss-scss#79]
It seems that only inline comments outside rules are converted.

For example,
```scss
// comment1
a,
// comment2
b {
  color: red;
}
```
Expect
```css
/* comment1*/
a,
/* comment2*/
b {
  color: red;
}
```
but get
```css
/* comment1*/
a,
// comment2
b {
  color: red;
}
```
